### ISSUE TITLE
Errors after downloading Pokémon Studio prevent me from opening it

### ISSUE THREAD

**Issue by as-Circe** [PokemonWorkshop/PokemonStudio#231]
### Description

When I try to download the MacOS file, it downloads Pokémon Studio just fine, but once I try and open the app, it tells me that the file is 'damaged'? This happens with both the 2.0.2 and 2.0.1 releases. 

![image](https://github.com/PokemonWorkshop/PokemonStudio/assets/110109337/b75a93ec-11cc-4a9f-a033-42a25f532a2a)
Apologies that it's in Dutch, but the translation is:
_"Pokemon Studio is damaged and cannot be opened. Move it to the trash bin. ¶ Chrome downloaded this file today at 17:22."_ 

Is there something I'm doing wrong?

**Comment by NuriYuri** [comment]
Hello, you did nothing wrong, this is just MacOS basic safety stuff (because we don't have the money to pay for very expensive coding certificates and the Apple fees to even be recognized as developpers).

To fix that issue:
1. Open a terminal in the folder where `Pokemon Studio.app` is located.
2. Run the following command: `sudo xattr -cr "Pokemon Studio.app"`
3. Double click on `Pokemon Studio.app`, it should run.

Please, make sure you're using the latest version :)

Note: If you have an Intel Mac, it will unfortunately not work because Studio is built to work on Apple Silicon (we don't have any device to build for non Apple Silicon Macs).

**Comment by as-Circe** [comment]
@NuriYuri thank you!! I will try this - and yes I have the apple M2 chip in my computer so it should work.

**Comment by NuriYuri** [comment]
Yes it should hopefully work. (I believe it worked for someone else with the same chip)

**Comment by AerunDev** [comment]
@as-Circe Any update? Feel free to close this issue if it works. 😄
