### ISSUE TITLE
Fix the wording about the trainer victory and defeat music

### ISSUE THREAD

**Issue by AerunDev** [PokemonWorkshop/PokemonStudio#99]
As an User
I would like the wording about the trainer victory and defeat music to be fixed
So that I understand better which one can be used in which case

**Comment by NuriYuri** [comment]
When a task request to change something, can we please state explicitly what's the current state and what's the expected state of the thing.

It seems the thing is probably already fixed in the app:

![Image](https://github.com/PokemonWorkshop/PokemonStudio/assets/7335788/1fd0701a-01ce-4bdd-87a5-97dadb24eeb1)

Please check.

**Comment by AerunDev** [comment]
Yeah seems like someone fixed that. @Palbolsky ?

**Comment by Palbolsky** [comment]
Obviously the issue never existed. Basically when I made the page I improved the wording but Figma wasn't updated.

**Comment by AerunDev** [comment]
Thanks, I'll close it!
